version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: enchelin-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: enchelin-db
      POSTGRES_USER: flint
      POSTGRES_PASSWORD: flint1
    volumes:
      - enchelin-db-data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: enchelin-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/enchelin-db
      SPRING_DATASOURCE_USERNAME: flint
      SPRING_DATASOURCE_PASSWORD: flint1
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    restart: always

volumes:
  enchelin-db-data: